#!python

Import('env')

sources = [
    'colors.c',
    'common.c',
    'file.c',
    'filter.c',
    'generate.c',
    'layers.c',
    'transform.c'
]

lib = env.StaticLibrary(target='texproma', source=sources)
Clean(lib, Glob('*~'))
