
import platform
import SCons.Builder
import SCons.Action

env = Environment()

env.Append(CXXFLAGS = '-std=c++11')
env.Append(CCFLAGS = '-g -Og')
env.Append(LINKFLAGS = '-g')

env.ParseConfig('pkg-config --cflags sdl2')
env.ParseConfig('pkg-config --libs sdl2')

SConscript('../libtexproma/SConscript', exports = 'env')
SConscript('SConscript', exports = 'env')

env.Prepend(LIBS =['m', 'texproma', 'nodes', 'boost_unit_test_framework']) 
env.Prepend(LIBPATH =[Dir('../libtexproma/').abspath, Dir('.').abspath]) 
env.Prepend(CPPPATH =[Dir('../libtexproma/').abspath, Dir('.').abspath]) 

SConscript('tests/SConscript', exports = 'env')
prog = env.Program(target = 'nodesInterface', source = ['main.cpp']) 
Clean(prog, [Glob('*~')])