
Import('env')


runner = Builder(action = './$SOURCE 2> $TARGET')
env.Append(BUILDERS = {'Run' : runner})

sources = [
    'DataTest.cpp',
    'TpmWrapperTests.cpp',
    'NodeTests.cpp'
]

tests = env.Program(target = 'NodesTests', source=sources);
testRunCmd = env.Run('test.log', 'NodesTests')
env.AlwaysBuild(testRunCmd);
Clean(tests, Glob('*~'))

# for test in tests:
# 	testBinary = env.Program(target=test, source=[test+'.cpp'])
# 	testRunCmd = env.Run(test + '.dummy', test)
# 	env.AlwaysBuild(testRunCmd)
# 	Clean(testBinary, Glob('*~'))
