
Import('env')


runner = Builder(action = './$SOURCE')
env.Append(BUILDERS = {'Run' : runner})

tests = [
    'DataTest',
    'TpmWrapperTests'
]

for test in tests:
	testBinary = env.Program(target=test, source=[test+'.cpp'])
	testRunCmd = env.Run(test + '.dummy', test)
	env.AlwaysBuild(testRunCmd)
	Clean(testBinary, Glob('*~'))
